//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubiconERPv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGR0ROTBOMCONTENT
    {
        public string COMCODE { get; set; }
        public string ROTDOCTYPE { get; set; }
        public string ROTDOCNUM { get; set; }
        public System.DateTime ROTDOCFROM { get; set; }
        public System.DateTime ROTDOCUNTIL { get; set; }
        public string MATDOCTYPE { get; set; }
        public string MATDOCNUM { get; set; }
        public int OPRNUM { get; set; }
        public string BOMDOCTYPE { get; set; }
        public string BOMDOCNUM { get; set; }
        public int CONTENTNUM { get; set; }
        public string COMPONENT { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
    
        public virtual BSMGR0GEN001 BSMGR0GEN001 { get; set; }
    }
}
