//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubiconERPv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGR0CCMTEXT
    {
        public string COMCODE { get; set; }
        public string CCMDOCTYPE { get; set; }
        public string CCMDOCNUM { get; set; }
        public System.DateTime CCMDOCFROM { get; set; }
        public System.DateTime CCMDOCUNTIL { get; set; }
        public string LANCODE { get; set; }
        public string CCMSTEXT { get; set; }
        public string CCMLTEXT { get; set; }
    
        public virtual BSMGR0GEN001 BSMGR0GEN001 { get; set; }
    }
}
