//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubiconERPv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGR0WCM001
    {
        public string COMCODE { get; set; }
        public string DOCTYPE { get; set; }
        public string DOCTYPETEXT { get; set; }
        public int ISPASSIVE { get; set; }
    
        public virtual BSMGR0GEN001 BSMGR0GEN001 { get; set; }
    }
}
